-- Plugins initialization
require("nvim-treesitter.configs").setup(require("plugins.config.treesitter"))
require("luasnip").setup() -- luasnip needs to be invoked before cmp.
-- require("cmp").setup(require("plugins.config.compl"))
require("blink.cmp").setup(require("plugins.config.blink-cmp"))
require("fzf-lua").setup()
-- require("null-ls").setup(require("plugins.config.null-ls"))
require("fidget").setup()
require("Comment").setup()
require('lualine').setup(require("plugins.config.lualine"))
require("ibl").setup()
require("gitsigns").setup()
require("which-key").setup(require("plugins.config.which-key"))
require("nvim-autopairs").setup(require("plugins.config.nvim-autopairs"))
require("neo-tree").setup(require("plugins.config.neotree"))
require("noice").setup(require("plugins.config.noice"))
require("catppuccin").setup(require("plugins.config.catppuccin"))
-- require("trouble").setup(require("plugins.config.trouble"))
-- require("neogit").setup()
-- require("neorg").setup(require("plugins.config.neorg"))
require("hop").setup()
require("todo-comments").setup(require("plugins.config.todo-comments"))
-- require("zen-mode").setup(require("plugins.config.zen-mode"))
require("go").setup()
require("lazydev").setup()
